name = "xpense-api"
main = "src/index.ts"
compatibility_date = "2024-04-14"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "xpense-db"
database_id = "494906c3-ccff-42a9-a38a-94a2a011c545"

# KV for session management
[[kv_namespaces]]
binding = "SESSIONS"
id = "8b42d48ad1334e0586d8c8a2156d549f"

# Environment variables
[vars]
ENVIRONMENT = "production"
SITE_NAME = "Xpense App"

# CORS configuration
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
